package com.myhotspot.app.platform.root

import android.content.Context
import android.os.Environment
import dagger.hilt.android.qualifiers.ApplicationContext
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import java.io.File
import javax.inject.Inject
import javax.inject.Singleton

@Singleton
class MagiskScriptExporter @Inject constructor(
    @ApplicationContext private val context: Context,
    private val shell: RootShellManager
) {

    fun generateScriptContent(ttlValue: Int, blockIpv6: Boolean, redirectDns: Boolean): String {
        return """
            #!/system/bin/sh
            # TTL Hotspot Magisk Boot Script
            # Automatically generated by TTL Hotspot
            
            # Wait for boot completion
            while [ "$(getprop sys.boot_completed)" != "1" ]; do
                sleep 2
            done
            sleep 5
            
            # 1. Enable IP Forwarding
            echo 1 > /proc/sys/net/ipv4/ip_forward
            sysctl -w net.ipv4.ip_forward=1
            sysctl -w net.ipv6.conf.all.forwarding=1
            
            # 2. Set Kernel Default TTL
            sysctl -w net.ipv4.ip_default_ttl=$ttlValue
            sysctl -w net.ipv6.conf.all.hop_limit=$ttlValue
            
            # 3. Apply iptables mangle rules for all outbound packets
            iptables -t mangle -D POSTROUTING -j TTL --ttl-set $ttlValue 2>/dev/null
            iptables -t mangle -I POSTROUTING -j TTL --ttl-set $ttlValue
            
            ip6tables -t mangle -D POSTROUTING -j HL --hl-set $ttlValue 2>/dev/null
            ip6tables -t mangle -I POSTROUTING -j HL --hl-set $ttlValue
            
            # 4. Ensure MASQUERADE
            iptables -t nat -A POSTROUTING -j MASQUERADE 2>/dev/null
            
            ${if (blockIpv6) "# Block IPv6\nip6tables -I FORWARD -j DROP\n" else ""}
            ${if (redirectDns) "# Redirect DNS\niptables -t nat -I PREROUTING -p udp --dport 53 -j DNAT --to-destination 8.8.8.8:53\n" else ""}
            
            log -t TTL_HOTSPOT "TTL Hotspot boot script executed with TTL=$ttlValue"
        """.trimIndent()
    }

    suspend fun installToMagiskServiceD(ttlValue: Int, blockIpv6: Boolean, redirectDns: Boolean): Boolean = withContext(Dispatchers.IO) {
        if (!shell.isRootAvailable()) return@withContext false

        val script = generateScriptContent(ttlValue, blockIpv6, redirectDns)
        val tempFile = File(context.cacheDir, "ttl_hotspot.sh")
        tempFile.writeText(script)

        val targetDir = "/data/adb/service.d"
        val targetPath = "$targetDir/ttl_hotspot.sh"

        val cmds = listOf(
            "mkdir -p $targetDir",
            "cp ${tempFile.absolutePath} $targetPath",
            "chmod 755 $targetPath",
            "chown root:root $targetPath"
        )

        val results = cmds.map { shell.execute(it) }
        tempFile.delete()
        results.all { it.isSuccess }
    }

    suspend fun exportToDownloads(ttlValue: Int, blockIpv6: Boolean, redirectDns: Boolean): String? = withContext(Dispatchers.IO) {
        try {
            val script = generateScriptContent(ttlValue, blockIpv6, redirectDns)
            val downloadDir = Environment.getExternalStoragePublicDirectory(Environment.DIRECTORY_DOWNLOADS)
            if (!downloadDir.exists()) downloadDir.mkdirs()
            val file = File(downloadDir, "ttl_hotspot_magisk.sh")
            file.writeText(script)
            file.absolutePath
        } catch (_: Exception) {
            null
        }
    }
}
